DEFAULT_DELIMITER = " "
DEFAULT_CRON_SEGMENTS_COUNT = 6
DEFAULT_LIST_DELIMITER = ","
DEFAULT_RANGE_DELIMITER = "-"
DEFAULT_ALL_SELECTOR = "*"
DEFAULT_STEP_DELIMITER = "/"
DEFAULT_SEGMENT_TYPE_ORDER = [
    "MINUTE",
    "HOUR",
    "DAY_OF_THE_MONTH",
    "MONTH",
    "DAY_OF_THE_WEEK",
    "COMMAND",
]
DEFAULT_TITLE_FILL_WIDTH = 14
